[theme]
primaryColor = "#f70015"         # Your main company accent color (e.g., buttons, links)
backgroundColor = "#FFFFFF"      # The main app background
secondaryBackgroundColor = "#8eaff1" # Sidebar and input box backgrounds
textColor = "#262730"            # Main text color